# create pipeline with some name
name: day4 cicd pipeline
# trigger section - when the pipeline should start
on:
  push:
    branches:
      - "dev"
# jobs for performing operations
jobs:
  wally-image-build:
    runs-on: ubuntu-latest
    # this server will be provisioned by github backend for this job
    steps:
      - name: run some basic commands on above server to do verification
        run: |
          uname -r
          whoami
          cat /etc/os-release
          docker version
          docker-compose version
      - name: using pre-designed gh workflow to get copy gitrepo code to runners machine
        uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        with:
          projectBaseDir: ./python-app-secret
          args: >
            -Dsonar.projectKey=wally-sq-project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - name: verify github code
        run: |
          ls -ltra
          cd python-app-secret
          docker-compose up -d
          sleep 2
          docker-compose ps
          sleep 1
          docker-compose logs
      - name: Build an image from Dockerfile
        run: |
          cd python-app-secret
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wallys:bmov${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wallys:bmov${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: try to login from runner to docker hub account 
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: pushing image to docker hub 
        run: |
          echo "please wait while image is getting pushed"
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wallys:bmov${{ github.sha }}
      - name: installing node 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: install npm modules for ecs
        run: |
          node -v
          cd ecs
          npm install
      - name: setup aws login details
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: cdk deploy esc code
        run: |
          cd ecs
          npx cdk bootstrap
          npx cdk deploy --no-rollback --require-approval never
      # - name: check cdk version details
      #   run: |
      #     node -v
      #     npm -v
      #     cdk --version
      #     aws --version 
