# create pipeline with some name
name: wally app containerization pipeline
# trigger section - when the pipeline should start
on:
  push:
    branches:
      - "main"

# jobs for performing operations
jobs:
  wally-image-build:
    runs-on: ubuntu-latest
    # this server will be provisioned by github backend for this job
    steps:
      - name: run some basic commands on above server to do verification
        run: |
          uname -r
          whoami
          cat /etc/os-release
          docker version
          docker-compose version
      - name: using pre-designed gh workflow to get copy gitrepo code to runners machine
        uses: actions/checkout@v4
      - name: verify github code
        run: |
          ls -ltra
          docker-compose up -d
          sleep 2
          docker-compose ps
      - name: verify hc page exists
        run: |
          echo "Checking HC page"
          curl --head --silent http://localhost:1984/health.html | head -n 1
          