# create pipeline with some name
name: wally multipjob project demo pipeline
# trigger section - when the pipeline should start
on:
  push:
    branches:
      - "dev"

#creating multiple jobs
jobs:
  wally-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarscanner
        run: |
          pwd
          whoami
          sonar-scanner --version
      - name: retrieve github code
        uses: actions/checkout@v4
      - name: local sonarqube scan
        run: |
          pwd
          sonar-scanner.bat -D"sonar.projectKey=wally-multi-demo" -D"sonar.sources=." -D"sonar.host.url=http://44.219.46.64:9000/" -D"sonar.token=sqp_0074b5aeed064dc7fc283433cc79068176f73167"
      - name: use upload artifacts # to save and use artifacts in the next job
        uses: actions/upload-artifact@v4
        with:
          name: wally-artifact
          path: |
            .
            !**/.git*
            !**/*.md
            !**/.scannerwork
  wally-build-job:
    runs-on: ubuntu-latest
    needs: wally-sast-job
    steps:
      - name: general checks
        run: |
          echo "docker related details"
          docker version
          docker-compose --version
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wally-artifact
          path: .
      - name: docker compose to build and test
        run: |
          ls -a
          docker-compose up -d --build
          sleep 2
          docker-compose ps
      - name: verify HC page by access it using curl
        run: |
          echo "Checking HC page"
          curl --head --silent http://localhost:1984/health.html | head -n 1
      - name: pusing above image to ecr
        run: |
        or
        uses:
      - id: ecr-publish
        uses: bitovi/github-actions-ecr-publish@v0.1.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          aws_ecr_repo_name: 751136288263.dkr.ecr.us-east-1.amazonaws.com/bmo-webui-app
          image_tag: wallywebuiV2


    # steps:
    #   - name: login from runner to docker hub account
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    #   - name: build and push to docker hub
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: . # location of Dockerfile
    #       push: true
    #       tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wally-newapp:version01
    #   - name: docker logout from runner after pushing image
    #     run: docker logout